# Change these first
owner: fareez2 # Your GitHub organization or username, where this repository lives
repo: jakim-up # The name of this repository

sites:
  - name: Jakim MyDQ
    url: https://mydq.islam.gov.my/
  - name: E-solat
    url: https://www.e-solat.gov.my/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /jakim-up
  logoUrl: https://i1.wp.com/mysyabab.com/wp-content/uploads/2017/09/jakim-logo-vector-720x340.png?fit=720%2C340&ssl=1
  name: JakimUp
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Monitor few Jakim site
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/fareez2/jakim-up

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
